-- Migration des paiements - Batch 49/49
-- Généré automatiquement
-- Paiements 48001 à 48076

-- Insertion des paiements
INSERT INTO payments (id, sale_id, method, amount)
VALUES
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 47994), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 47995), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 47996), 'contactless', 20.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 47997), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 47998), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 47999), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48000), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48001), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48002), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48003), 'contactless', 20.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48004), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48005), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48006), 'contactless', 100.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48007), 'contactless', 50.15),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48008), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48009), 'contactless', 20.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48010), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48011), 'contactless', 16.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48012), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48013), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48014), 'contactless', 73.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48015), 'contactless', 20.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48016), 'cash', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48017), 'contactless', 20.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48018), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48019), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48020), 'contactless', 16.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48021), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48022), 'contactless', 20.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48023), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48024), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48025), 'contactless', 20.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48026), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48027), 'contactless', 51.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48028), 'card', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48029), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48030), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48031), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48032), 'contactless', 99.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48033), 'contactless', 16.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48034), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48035), 'contactless', 20.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48036), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48037), 'cash', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48038), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48039), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48040), 'contactless', 20.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48041), 'contactless', 20.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48042), 'contactless', 20.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48043), 'contactless', 25.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48044), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48045), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48046), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48047), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48048), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48049), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48050), 'cash', 16.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48051), 'contactless', 20.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48052), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48053), 'contactless', 83.6),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48054), 'contactless', 50.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48055), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48056), 'cash', 20.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48057), 'contactless', 16.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48058), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48059), 'contactless', 18.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48060), 'contactless', 30.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48061), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48062), 'card', 35.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48063), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48064), 'contactless', 20.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48065), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48066), 'card', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48067), 'contactless', 50.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48068), 'contactless', 28.0),
(gen_random_uuid(), (SELECT new_id FROM migration_sale_mapping WHERE old_id = 48069), 'contactless', 28.0)
ON CONFLICT DO NOTHING;

-- Vérification finale
SELECT 'Paiements migrés:' as info, COUNT(*) as total FROM payments;
